name: Bump and Release (main)

on:
  push:
    branches:
      - main

jobs:
  bump:
    name: Bump version (semantic-release)
    uses: ./.github/workflows/bump.yml
    secrets:
      RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
